In [1]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [8, 9, 10]])

In [2]:

B = np.triu(A)
print("Upper triangular matrix\n",B)

Upper triangular matrix
 [[ 1  2  3]
 [ 0  5  6]
 [ 0  0 10]]


In [3]:

C = np.tril(B)
print("Lower triangular matrix\n",C)

Lower triangular matrix
 [[ 1  0  0]
 [ 0  5  0]
 [ 0  0 10]]


In [4]:
transposed_matrix = C.transpose()
print("Transpose of a:\n" , transposed_matrix)

Transpose of a:
 [[ 1  0  0]
 [ 0  5  0]
 [ 0  0 10]]
